# Generated by Django 5.2 on 2025-05-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('imagen', models.ImageField(null=True, upload_to='images/', verbose_name='Imagen')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('descripcion', models.TextField(max_length=100, verbose_name='Descripcion')),
                ('categoria', models.CharField(choices=[('TELAS', 'Telas'), ('MERCERIA', 'Mercería'), ('ACCESORIOS', 'Accesorios'), ('DECORACION', 'Decoracion'), ('HOGAR', 'Hogar')], max_length=30, verbose_name='Categoría')),
            ],
        ),
    ]
