# Generated by Django 5.2 on 2025-05-06 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merceria', '0003_carrito_itemcarrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='ItemCarrito',
        ),
    ]
